aws_region       = "us-east-1"
environment      = "dev"
project_name     = "gift-list"
cors_origin      = "http://localhost:3000"
google_client_id = "your-google-client-id.apps.googleusercontent.com"
